

logging:
  level:
    web: INFO

server:
  port: 8080


spring:
  security:
    oauth2:
      client:
        # setting oauth source
        provider:
          baidu:
            authorization-uri: http://openapi.baidu.com/oauth/2.0/authorize
            token-uri: https://openapi.baidu.com/oauth/2.0/token
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            jwk-set-uri: https://gitee.com/api/v5/user/keys
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
        registration:
          # https://openauth.baidu.com/doc/
          # default redirect uri = http://localhost:8080/login/oauth2/code/xxxxxx
          # {baseUrl}/login/oauth2/code/{registrationId}
          baidu:
            authorization-grant-type: authorization_code
            client-id: oW8e11A2svTWnnrLnzckRNwN
            client-secret: u77rS2fBPdQMjAGtZinwgy3Y9Wm4vW8g
            provider: baidu
            redirect-uri: http://localhost:8080/v1/oauth2/baidu/callback
          gitee:
            authorization-grant-type: authorization_code
            client-id: d996d4579a8c1f7f043dfd0d5c1a63f1c301ca06587a8fedd54f661cb8088c8e
            client-secret: 8a5802693fe02d1fc31f01a6191fcba2fb08f829edc22359b60f70c485bc2eb1
            provider: gitee
            redirect-uri: http://localhost:8080/v1/oauth2/gitee/callback
          # OAuth2 for github
          github:
            authorization-grant-type: authorization_code
            client-id: b57628e055f1ef03b4a6
            client-secret: 6fbbe4360f128206d622f6c7ea15f22807f9785b
            provider: github
            redirect-uri: http://localhost:8080/v1/oauth2/github/callback
  mvc:
    view:
      prefix: /
      suffix: .html





